#ifndef EIGHTVO_VERSION_H
#define EIGHTVO_VERSION_H

#define EIGHTVO_VERSION_MAJOR 0
#define EIGHTVO_VERSION_MINOR 4
#define EIGHTVO_VERSION_PATCH 0
#define EIGHTVO_VERSION_STRING "0.4.0-dev"

#endif /* EIGHTVO_VERSION_H */
