#ifndef LECTERN0_VERSION_H
#define LECTERN0_VERSION_H

#define LECTERN0_VERSION_MAJOR 0
#define LECTERN0_VERSION_MINOR 4
#define LECTERN0_VERSION_PATCH 0
#define LECTERN0_VERSION_STRING "0.4.0-dev"

#endif /* LECTERN0_VERSION_H */
