#ifndef OCTAVO_VERSION_H
#define OCTAVO_VERSION_H

#define OCTAVO_VERSION_MAJOR 0
#define OCTAVO_VERSION_MINOR 4
#define OCTAVO_VERSION_PATCH 0
#define OCTAVO_VERSION_STRING "0.4.0-dev"

#endif /* OCTAVO_VERSION_H */
